# Generated by Django 3.1.6 on 2021-02-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210205_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='Week Start:'),
        ),
    ]
