# Generated by Django 3.1.6 on 2021-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210205_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='department',
        ),
        migrations.AddField(
            model_name='report',
            name='depto',
            field=models.CharField(choices=[('01', 'Department 01: Novos Biopesticidas'), ('02', 'Department 02: Proteção de Culturas Específicas'), ('03', 'Department 03: Gestão de Dados e Análise de Risco'), ('04', 'Department 04: Monitorização e Diagnóstico'), ('05', 'Department 05: Novas Formulações e Matrizes para a Aplicação de Biopesticidas'), ('06', 'Department 06: Gestão')], default='01', max_length=100, verbose_name='Department:'),
        ),
    ]
