# Generated by Django 3.1.5 on 2021-02-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210205_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='Week Starts on:'),
        ),
    ]
