# Generated by Django 3.1.5 on 2021-02-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210211_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name:')),
                ('date', models.DateField(verbose_name='Week Starts on:')),
                ('research_activities', models.TextField(verbose_name='Research Activities:')),
                ('internal_meetings', models.TextField(verbose_name='Internal Meetings:')),
                ('external_meetings', models.TextField(verbose_name='External Meetings and Stakeholders Engagement:')),
                ('service_tools', models.TextField(verbose_name='Service / Tools Development:')),
                ('grant', models.TextField(verbose_name='Grant / Calls Preparation:')),
                ('training', models.TextField(verbose_name='Training / Webnars Attendance:')),
            ],
        ),
    ]
